SELECT TOP (1000) [index]
      ,[% AIC Retention]
      ,[15% Agency Commission]
      ,[2019 Proposed Premium (capped)]
      ,[ALEFoodSpoilagePremium]
      ,[Address]
      ,[Admin1Code]
      ,[Admin1Name]
      ,[Admin2Name]
      ,[Agency]
      ,[Agency Cm %]
      ,[Aon @ 5%]
      ,[Bldg TIV]
      ,[Building Coverage]
      ,[Building Premium]
      ,[CAT Load]
      ,[Can/End Effective Date]
      ,[Cancel Code]
      ,[City]
      ,[City1]
      ,[CityName]
      ,[Cnts TIV]
      ,[Comm + AIC]
      ,[Const. Date]
      ,[ConstructionType]
      ,[ConstructionType_x]
      ,[ConstructionType_y]
      ,[Contents Coverage]
      ,[Contents Premium]
      ,[Counter proposal]
      ,[County]
      ,[Current Month Due AON (80%)]
      ,[Date Recvd]
      ,[Deductible]
      ,[Excess/Shortage]
      ,[FCEAS]
      ,[February 19 Inforce?]
      ,[Flood Zone]
      ,[FloodScore]
      ,[FloodScore Bracket]
      ,[Florida County Classification]
      ,[Foundation]
      ,[GeoResolution]
      ,[GeoResolution Desc]
      ,[GeoResolutionCode]
      ,[ICC Premium]
      ,[IF Gross AAL]
      ,[In scope (orig)]
      ,[In scope.]
      ,[Insured]
      ,[LOCNAME]
      ,[Latitude]
      ,[LineName]
      ,[Lloyd’s/Illinois Union]
      ,[Longitude]
      ,[NAIC Number]
      ,[NJ Only#]
      ,[Number of Stories]
      ,[OR Fire Marshl Tax]
      ,[Occupancy]
      ,[Occupancy_x]
      ,[Occupancy_y]
      ,[Overpay]
      ,[Pay Due AIC Less Agy. Comm.]
      ,[Payment Due Illinois Union]
      ,[Payment Due Illinois Union-  20%]
      ,[Payment Due Lloyd's]
      ,[Payment Due Lloyd's - 80%]
      ,[Policy Adm. Charge]
      ,[Policy Effective Date]
      ,[Policy Expire Date]
      ,[Policy Nbr]
      ,[Policy Number_x]
      ,[Policy Type]
      ,[PostalCode]
      ,[Premium]
      ,[Prior Losses - Y or N]
      ,[ProgCode]
      ,[Property Address 1]
      ,[Property Address 2]
      ,[Property Address 2_x]
      ,[Property Address 2_y]
      ,[Reason for Cancellation]
      ,[ResolutionDescription]
      ,[Roll Over?]
      ,[SL Clearinghouse Fee]
      ,[SL License]
      ,[SL Tax]
      ,[Section ]
      ,[Service/Stamping Fee]
      ,[SquareFootage]
      ,[State]
      ,[State1]
      ,[StreetAddress]
      ,[Surplus Lines Agent/Agency]
      ,[SwimmingPoolCleanoutPremium]
      ,[TOTAL]
      ,[Total Policy Amount]
      ,[Total as %]
      ,[Type]
      ,[Written Premium (current Oct)]
      ,[Wrt-Offs]
      ,[Year]
      ,[Year Built]
      ,[Zip]
      ,[Zip1]
      ,[Zone]
      ,[29/05 Counter]
      ,[14/06 Counter]
  FROM [PricingDevelopment].[bdx].[NFSRiskBdx201904]